/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ImageAttachment
 */
public class ImageAttachmentTest {
    private final ImageAttachment model = new ImageAttachment();
    
    /**
     * Model tests for ImageAttachment
     */
    @Test
    public void testImageAttachment() {
        // TODO: test ImageAttachment
    }
    
    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }
    
    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }
    
    /**
     * Test the property 'display'
     */
    @Test
    public void displayTest() {
        // TODO: test display
    }
    
    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }
    
    /**
     * Test the property 'objectId'
     */
    @Test
    public void objectIdTest() {
        // TODO: test objectId
    }
    
    /**
     * Test the property 'parent'
     */
    @Test
    public void parentTest() {
        // TODO: test parent
    }
    
    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }
    
    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }
    
    /**
     * Test the property 'imageHeight'
     */
    @Test
    public void imageHeightTest() {
        // TODO: test imageHeight
    }
    
    /**
     * Test the property 'imageWidth'
     */
    @Test
    public void imageWidthTest() {
        // TODO: test imageWidth
    }
    
    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }
    
    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }
    
}
