/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for IpamVlansList200Response
 */
public class IpamVlansList200ResponseTest {
    private final IpamVlansList200Response model = new IpamVlansList200Response();
    
    /**
     * Model tests for IpamVlansList200Response
     */
    @Test
    public void testIpamVlansList200Response() {
        // TODO: test IpamVlansList200Response
    }
    
    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }
    
    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }
    
    /**
     * Test the property 'previous'
     */
    @Test
    public void previousTest() {
        // TODO: test previous
    }
    
    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }
    
}
