/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for NestedVirtualChassis
 */
public class NestedVirtualChassisTest {
    private final NestedVirtualChassis model = new NestedVirtualChassis();
    
    /**
     * Model tests for NestedVirtualChassis
     */
    @Test
    public void testNestedVirtualChassis() {
        // TODO: test NestedVirtualChassis
    }
    
    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }
    
    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }
    
    /**
     * Test the property 'display'
     */
    @Test
    public void displayTest() {
        // TODO: test display
    }
    
    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }
    
    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }
    
    /**
     * Test the property 'memberCount'
     */
    @Test
    public void memberCountTest() {
        // TODO: test memberCount
    }
    
}
