/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for PowerOutletTemplate
 */
public class PowerOutletTemplateTest {
    private final PowerOutletTemplate model = new PowerOutletTemplate();
    
    /**
     * Model tests for PowerOutletTemplate
     */
    @Test
    public void testPowerOutletTemplate() {
        // TODO: test PowerOutletTemplate
    }
    
    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }
    
    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }
    
    /**
     * Test the property 'display'
     */
    @Test
    public void displayTest() {
        // TODO: test display
    }
    
    /**
     * Test the property 'deviceType'
     */
    @Test
    public void deviceTypeTest() {
        // TODO: test deviceType
    }
    
    /**
     * Test the property 'moduleType'
     */
    @Test
    public void moduleTypeTest() {
        // TODO: test moduleType
    }
    
    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }
    
    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }
    
    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }
    
    /**
     * Test the property 'powerPort'
     */
    @Test
    public void powerPortTest() {
        // TODO: test powerPort
    }
    
    /**
     * Test the property 'feedLeg'
     */
    @Test
    public void feedLegTest() {
        // TODO: test feedLeg
    }
    
    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }
    
    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }
    
    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }
    
}
