/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for Type6
 */
public class Type06Test {
    private final Type6 model = new Type6();
    
    /**
     * Model tests for Type6
     */
    @Test
    public void testType6() {
        // TODO: test Type6
    }
    
    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }
    
    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }
    
}
