/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for WritableVirtualChassis
 */
public class WritableVirtualChassisTest {
    private final WritableVirtualChassis model = new WritableVirtualChassis();
    
    /**
     * Model tests for WritableVirtualChassis
     */
    @Test
    public void testWritableVirtualChassis() {
        // TODO: test WritableVirtualChassis
    }
    
    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }
    
    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }
    
    /**
     * Test the property 'display'
     */
    @Test
    public void displayTest() {
        // TODO: test display
    }
    
    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }
    
    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }
    
    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }
    
    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }
    
    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }
    
    /**
     * Test the property 'memberCount'
     */
    @Test
    public void memberCountTest() {
        // TODO: test memberCount
    }
    
    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }
    
    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }
    
}
