/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.codemakers.netbox.client.model.NestedCable;
import de.codemakers.netbox.client.model.NestedTag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WritablePowerFeed
 */
public class WritablePowerFeedTest {
    private final WritablePowerFeed model = new WritablePowerFeed();

    /**
     * Model tests for WritablePowerFeed
     */
    @Test
    public void testWritablePowerFeed() {
        // TODO: test WritablePowerFeed
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'display'
     */
    @Test
    public void displayTest() {
        // TODO: test display
    }

    /**
     * Test the property 'powerPanel'
     */
    @Test
    public void powerPanelTest() {
        // TODO: test powerPanel
    }

    /**
     * Test the property 'rack'
     */
    @Test
    public void rackTest() {
        // TODO: test rack
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'supply'
     */
    @Test
    public void supplyTest() {
        // TODO: test supply
    }

    /**
     * Test the property 'phase'
     */
    @Test
    public void phaseTest() {
        // TODO: test phase
    }

    /**
     * Test the property 'voltage'
     */
    @Test
    public void voltageTest() {
        // TODO: test voltage
    }

    /**
     * Test the property 'amperage'
     */
    @Test
    public void amperageTest() {
        // TODO: test amperage
    }

    /**
     * Test the property 'maxUtilization'
     */
    @Test
    public void maxUtilizationTest() {
        // TODO: test maxUtilization
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'markConnected'
     */
    @Test
    public void markConnectedTest() {
        // TODO: test markConnected
    }

    /**
     * Test the property 'cable'
     */
    @Test
    public void cableTest() {
        // TODO: test cable
    }

    /**
     * Test the property 'cableEnd'
     */
    @Test
    public void cableEndTest() {
        // TODO: test cableEnd
    }

    /**
     * Test the property 'linkPeers'
     */
    @Test
    public void linkPeersTest() {
        // TODO: test linkPeers
    }

    /**
     * Test the property 'linkPeersType'
     */
    @Test
    public void linkPeersTypeTest() {
        // TODO: test linkPeersType
    }

    /**
     * Test the property 'connectedEndpoints'
     */
    @Test
    public void connectedEndpointsTest() {
        // TODO: test connectedEndpoints
    }

    /**
     * Test the property 'connectedEndpointsType'
     */
    @Test
    public void connectedEndpointsTypeTest() {
        // TODO: test connectedEndpointsType
    }

    /**
     * Test the property 'connectedEndpointsReachable'
     */
    @Test
    public void connectedEndpointsReachableTest() {
        // TODO: test connectedEndpointsReachable
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    public void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

    /**
     * Test the property 'occupied'
     */
    @Test
    public void occupiedTest() {
        // TODO: test occupied
    }

}
