/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.codemakers.netbox.client.model.NestedVRF;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AvailableIP
 */
@JsonPropertyOrder({
  AvailableIP.JSON_PROPERTY_FAMILY,
  AvailableIP.JSON_PROPERTY_ADDRESS,
  AvailableIP.JSON_PROPERTY_VRF
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-31T18:36:37.665487300+02:00[Europe/Berlin]")
public class AvailableIP {
  public static final String JSON_PROPERTY_FAMILY = "family";
  private Integer family;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_VRF = "vrf";
  private JsonNullable<NestedVRF> vrf = JsonNullable.<NestedVRF>undefined();

  public AvailableIP() { 
  }

  @JsonCreator
  public AvailableIP(
    @JsonProperty(JSON_PROPERTY_FAMILY) Integer family, 
    @JsonProperty(JSON_PROPERTY_ADDRESS) String address
  ) {
  this();
    this.family = family;
    this.address = address;
  }

   /**
   * Get family
   * @return family
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FAMILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFamily() {
    return family;
  }




   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }




  public AvailableIP vrf(NestedVRF vrf) {
    this.vrf = JsonNullable.<NestedVRF>of(vrf);
    return this;
  }

   /**
   * Get vrf
   * @return vrf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public NestedVRF getVrf() {
        return vrf.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VRF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<NestedVRF> getVrf_JsonNullable() {
    return vrf;
  }
  
  @JsonProperty(JSON_PROPERTY_VRF)
  public void setVrf_JsonNullable(JsonNullable<NestedVRF> vrf) {
    this.vrf = vrf;
  }

  public void setVrf(NestedVRF vrf) {
    this.vrf = JsonNullable.<NestedVRF>of(vrf);
  }


  /**
   * Return true if this AvailableIP object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvailableIP availableIP = (AvailableIP) o;
    return Objects.equals(this.family, availableIP.family) &&
        Objects.equals(this.address, availableIP.address) &&
        equalsNullable(this.vrf, availableIP.vrf);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(family, address, hashCodeNullable(vrf));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvailableIP {\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

