/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.codemakers.netbox.client.JSON;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.*;
import java.util.Map.Entry;

/**
 * JournalEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T15:14:28.278845400+02:00[Europe/Berlin]")
public class JournalEntry {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;
    
    public static final String SERIALIZED_NAME_URL = "url";
    @SerializedName(SERIALIZED_NAME_URL)
    private URI url;
    
    public static final String SERIALIZED_NAME_DISPLAY = "display";
    @SerializedName(SERIALIZED_NAME_DISPLAY)
    private String display;
    
    public static final String SERIALIZED_NAME_ASSIGNED_OBJECT_TYPE = "assigned_object_type";
    @SerializedName(SERIALIZED_NAME_ASSIGNED_OBJECT_TYPE)
    private String assignedObjectType;
    
    public static final String SERIALIZED_NAME_ASSIGNED_OBJECT_ID = "assigned_object_id";
    @SerializedName(SERIALIZED_NAME_ASSIGNED_OBJECT_ID)
    private Integer assignedObjectId;
    
    public static final String SERIALIZED_NAME_ASSIGNED_OBJECT = "assigned_object";
    @SerializedName(SERIALIZED_NAME_ASSIGNED_OBJECT)
    private Map<String, String> assignedObject = null;
    
    public static final String SERIALIZED_NAME_CREATED = "created";
    @SerializedName(SERIALIZED_NAME_CREATED)
    private OffsetDateTime created;
    
    public static final String SERIALIZED_NAME_CREATED_BY = "created_by";
    @SerializedName(SERIALIZED_NAME_CREATED_BY)
    private Integer createdBy;
    
    public static final String SERIALIZED_NAME_KIND = "kind";
    @SerializedName(SERIALIZED_NAME_KIND)
    private Kind kind;
    
    public static final String SERIALIZED_NAME_COMMENTS = "comments";
    @SerializedName(SERIALIZED_NAME_COMMENTS)
    private String comments;
    
    public static final String SERIALIZED_NAME_TAGS = "tags";
    @SerializedName(SERIALIZED_NAME_TAGS)
    private List<NestedTag> tags = null;
    
    public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "custom_fields";
    @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
    private Object customFields;
    
    public static final String SERIALIZED_NAME_LAST_UPDATED = "last_updated";
    @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
    private OffsetDateTime lastUpdated;
    
    public JournalEntry() {
    }
    
    
    public JournalEntry(Integer id, URI url, String display, Map<String, String> assignedObject, OffsetDateTime created, OffsetDateTime lastUpdated) {
        this();
        this.id = id;
        this.url = url;
        this.display = display;
        this.assignedObject = assignedObject;
        this.created = created;
        this.lastUpdated = lastUpdated;
    }
    
    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Integer getId() {
        return id;
    }
    
    
    /**
     * Get url
     *
     * @return url
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public URI getUrl() {
        return url;
    }
    
    
    /**
     * Get display
     *
     * @return display
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public String getDisplay() {
        return display;
    }
    
    
    public JournalEntry assignedObjectType(String assignedObjectType) {
        
        this.assignedObjectType = assignedObjectType;
        return this;
    }
    
    /**
     * Get assignedObjectType
     *
     * @return assignedObjectType
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    
    public String getAssignedObjectType() {
        return assignedObjectType;
    }
    
    
    public void setAssignedObjectType(String assignedObjectType) {
        this.assignedObjectType = assignedObjectType;
    }
    
    
    public JournalEntry assignedObjectId(Integer assignedObjectId) {
        
        this.assignedObjectId = assignedObjectId;
        return this;
    }
    
    /**
     * Get assignedObjectId
     * minimum: 0
     * maximum: 9223372036854775807
     *
     * @return assignedObjectId
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    
    public Integer getAssignedObjectId() {
        return assignedObjectId;
    }
    
    
    public void setAssignedObjectId(Integer assignedObjectId) {
        this.assignedObjectId = assignedObjectId;
    }
    
    
    /**
     * Get assignedObject
     *
     * @return assignedObject
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Map<String, String> getAssignedObject() {
        return assignedObject;
    }
    
    
    /**
     * Get created
     *
     * @return created
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public OffsetDateTime getCreated() {
        return created;
    }
    
    
    public JournalEntry createdBy(Integer createdBy) {
        
        this.createdBy = createdBy;
        return this;
    }
    
    /**
     * Get createdBy
     *
     * @return createdBy
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Integer getCreatedBy() {
        return createdBy;
    }
    
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    
    
    public JournalEntry kind(Kind kind) {
        
        this.kind = kind;
        return this;
    }
    
    /**
     * Get kind
     *
     * @return kind
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Kind getKind() {
        return kind;
    }
    
    
    public void setKind(Kind kind) {
        this.kind = kind;
    }
    
    
    public JournalEntry comments(String comments) {
        
        this.comments = comments;
        return this;
    }
    
    /**
     * Get comments
     *
     * @return comments
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    
    public String getComments() {
        return comments;
    }
    
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    
    
    public JournalEntry tags(List<NestedTag> tags) {
        
        this.tags = tags;
        return this;
    }
    
    public JournalEntry addTagsItem(NestedTag tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }
    
    /**
     * Get tags
     *
     * @return tags
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public List<NestedTag> getTags() {
        return tags;
    }
    
    
    public void setTags(List<NestedTag> tags) {
        this.tags = tags;
    }
    
    
    public JournalEntry customFields(Object customFields) {
        
        this.customFields = customFields;
        return this;
    }
    
    /**
     * Get customFields
     *
     * @return customFields
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Object getCustomFields() {
        return customFields;
    }
    
    
    public void setCustomFields(Object customFields) {
        this.customFields = customFields;
    }
    
    
    /**
     * Get lastUpdated
     *
     * @return lastUpdated
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public OffsetDateTime getLastUpdated() {
        return lastUpdated;
    }
    
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JournalEntry journalEntry = (JournalEntry) o;
        return Objects.equals(this.id, journalEntry.id) && Objects.equals(this.url, journalEntry.url) && Objects.equals(this.display, journalEntry.display) && Objects.equals(this.assignedObjectType, journalEntry.assignedObjectType) && Objects.equals(this.assignedObjectId, journalEntry.assignedObjectId) && Objects.equals(this.assignedObject, journalEntry.assignedObject) && Objects.equals(this.created, journalEntry.created) && Objects.equals(this.createdBy, journalEntry.createdBy) && Objects.equals(this.kind, journalEntry.kind) && Objects.equals(this.comments, journalEntry.comments) && Objects.equals(this.tags, journalEntry.tags) && Objects.equals(this.customFields, journalEntry.customFields) && Objects.equals(this.lastUpdated, journalEntry.lastUpdated);
    }
    
    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(id, url, display, assignedObjectType, assignedObjectId, assignedObject, created, createdBy, kind, comments, tags, customFields, lastUpdated);
    }
    
    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JournalEntry {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    display: ").append(toIndentedString(display)).append("\n");
        sb.append("    assignedObjectType: ").append(toIndentedString(assignedObjectType)).append("\n");
        sb.append("    assignedObjectId: ").append(toIndentedString(assignedObjectId)).append("\n");
        sb.append("    assignedObject: ").append(toIndentedString(assignedObject)).append("\n");
        sb.append("    created: ").append(toIndentedString(created)).append("\n");
        sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
        sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
        sb.append("}");
        return sb.toString();
    }
    
    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
    
    
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;
    
    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("id");
        openapiFields.add("url");
        openapiFields.add("display");
        openapiFields.add("assigned_object_type");
        openapiFields.add("assigned_object_id");
        openapiFields.add("assigned_object");
        openapiFields.add("created");
        openapiFields.add("created_by");
        openapiFields.add("kind");
        openapiFields.add("comments");
        openapiFields.add("tags");
        openapiFields.add("custom_fields");
        openapiFields.add("last_updated");
        
        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("assigned_object_type");
        openapiRequiredFields.add("assigned_object_id");
        openapiRequiredFields.add("comments");
    }
    
    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     *
     * @throws IOException if the JSON Object is invalid with respect to JournalEntry
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (JournalEntry.openapiRequiredFields.isEmpty()) {
                return;
            } else { // has required fields
                throw new IllegalArgumentException(String.format("The required field(s) %s in JournalEntry is not found in the empty JSON string", JournalEntry.openapiRequiredFields.toString()));
            }
        }
        
        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!JournalEntry.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `JournalEntry` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
            }
        }
        
        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : JournalEntry.openapiRequiredFields) {
            if (jsonObj.get(requiredField) == null) {
                throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
            }
        }
        if (jsonObj.get("url") != null && !jsonObj.get("url").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url")
                    .toString()));
        }
        if (jsonObj.get("display") != null && !jsonObj.get("display").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `display` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display")
                    .toString()));
        }
        if (jsonObj.get("assigned_object_type") != null && !jsonObj.get("assigned_object_type").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `assigned_object_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assigned_object_type")
                    .toString()));
        }
        // validate the optional field `kind`
        if (jsonObj.getAsJsonObject("kind") != null) {
            Kind.validateJsonObject(jsonObj.getAsJsonObject("kind"));
        }
        if (jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `comments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comments")
                    .toString()));
        }
        JsonArray jsonArraytags = jsonObj.getAsJsonArray("tags");
        if (jsonArraytags != null) {
            // ensure the json data is an array
            if (!jsonObj.get("tags").isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags")
                        .toString()));
            }
            
            // validate the optional field `tags` (array)
            for (int i = 0; i < jsonArraytags.size(); i++) {
                NestedTag.validateJsonObject(jsonArraytags.get(i).getAsJsonObject());
            }
            ;
        }
    }
    
    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!JournalEntry.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'JournalEntry' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<JournalEntry> thisAdapter = gson.getDelegateAdapter(this, TypeToken.get(JournalEntry.class));
            
            return (TypeAdapter<T>) new TypeAdapter<JournalEntry>() {
                @Override
                public void write(JsonWriter out, JournalEntry value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }
                
                @Override
                public JournalEntry read(JsonReader in) throws IOException {
                    JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                    validateJsonObject(jsonObj);
                    return thisAdapter.fromJsonTree(jsonObj);
                }
                
            }.nullSafe();
        }
    }
    
    /**
     * Create an instance of JournalEntry given an JSON string
     *
     * @param jsonString JSON string
     *
     * @return An instance of JournalEntry
     *
     * @throws IOException if the JSON string is invalid with respect to JournalEntry
     */
    public static JournalEntry fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, JournalEntry.class);
    }
    
    /**
     * Convert an instance of JournalEntry to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

