/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.codemakers.netbox.client.JSON;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/**
 * NestedModule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T15:14:28.278845400+02:00[Europe/Berlin]")
public class NestedModule {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;
    
    public static final String SERIALIZED_NAME_URL = "url";
    @SerializedName(SERIALIZED_NAME_URL)
    private URI url;
    
    public static final String SERIALIZED_NAME_DISPLAY = "display";
    @SerializedName(SERIALIZED_NAME_DISPLAY)
    private String display;
    
    public static final String SERIALIZED_NAME_DEVICE = "device";
    @SerializedName(SERIALIZED_NAME_DEVICE)
    private NestedDevice device;
    
    public static final String SERIALIZED_NAME_MODULE_BAY = "module_bay";
    @SerializedName(SERIALIZED_NAME_MODULE_BAY)
    private ModuleNestedModuleBay moduleBay;
    
    public static final String SERIALIZED_NAME_MODULE_TYPE = "module_type";
    @SerializedName(SERIALIZED_NAME_MODULE_TYPE)
    private NestedModuleType moduleType;
    
    public NestedModule() {
    }
    
    
    public NestedModule(Integer id, URI url, String display) {
        this();
        this.id = id;
        this.url = url;
        this.display = display;
    }
    
    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Integer getId() {
        return id;
    }
    
    
    /**
     * Get url
     *
     * @return url
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public URI getUrl() {
        return url;
    }
    
    
    /**
     * Get display
     *
     * @return display
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public String getDisplay() {
        return display;
    }
    
    
    public NestedModule device(NestedDevice device) {
        
        this.device = device;
        return this;
    }
    
    /**
     * Get device
     *
     * @return device
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public NestedDevice getDevice() {
        return device;
    }
    
    
    public void setDevice(NestedDevice device) {
        this.device = device;
    }
    
    
    public NestedModule moduleBay(ModuleNestedModuleBay moduleBay) {
        
        this.moduleBay = moduleBay;
        return this;
    }
    
    /**
     * Get moduleBay
     *
     * @return moduleBay
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public ModuleNestedModuleBay getModuleBay() {
        return moduleBay;
    }
    
    
    public void setModuleBay(ModuleNestedModuleBay moduleBay) {
        this.moduleBay = moduleBay;
    }
    
    
    public NestedModule moduleType(NestedModuleType moduleType) {
        
        this.moduleType = moduleType;
        return this;
    }
    
    /**
     * Get moduleType
     *
     * @return moduleType
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public NestedModuleType getModuleType() {
        return moduleType;
    }
    
    
    public void setModuleType(NestedModuleType moduleType) {
        this.moduleType = moduleType;
    }
    
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NestedModule nestedModule = (NestedModule) o;
        return Objects.equals(this.id, nestedModule.id) && Objects.equals(this.url, nestedModule.url) && Objects.equals(this.display, nestedModule.display) && Objects.equals(this.device, nestedModule.device) && Objects.equals(this.moduleBay, nestedModule.moduleBay) && Objects.equals(this.moduleType, nestedModule.moduleType);
    }
    
    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(id, url, display, device, moduleBay, moduleType);
    }
    
    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NestedModule {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    display: ").append(toIndentedString(display)).append("\n");
        sb.append("    device: ").append(toIndentedString(device)).append("\n");
        sb.append("    moduleBay: ").append(toIndentedString(moduleBay)).append("\n");
        sb.append("    moduleType: ").append(toIndentedString(moduleType)).append("\n");
        sb.append("}");
        return sb.toString();
    }
    
    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
    
    
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;
    
    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("id");
        openapiFields.add("url");
        openapiFields.add("display");
        openapiFields.add("device");
        openapiFields.add("module_bay");
        openapiFields.add("module_type");
        
        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }
    
    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     *
     * @throws IOException if the JSON Object is invalid with respect to NestedModule
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (NestedModule.openapiRequiredFields.isEmpty()) {
                return;
            } else { // has required fields
                throw new IllegalArgumentException(String.format("The required field(s) %s in NestedModule is not found in the empty JSON string", NestedModule.openapiRequiredFields.toString()));
            }
        }
        
        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!NestedModule.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NestedModule` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
            }
        }
        if (jsonObj.get("url") != null && !jsonObj.get("url").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url")
                    .toString()));
        }
        if (jsonObj.get("display") != null && !jsonObj.get("display").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `display` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display")
                    .toString()));
        }
        // validate the optional field `device`
        if (jsonObj.getAsJsonObject("device") != null) {
            NestedDevice.validateJsonObject(jsonObj.getAsJsonObject("device"));
        }
        // validate the optional field `module_bay`
        if (jsonObj.getAsJsonObject("module_bay") != null) {
            ModuleNestedModuleBay.validateJsonObject(jsonObj.getAsJsonObject("module_bay"));
        }
        // validate the optional field `module_type`
        if (jsonObj.getAsJsonObject("module_type") != null) {
            NestedModuleType.validateJsonObject(jsonObj.getAsJsonObject("module_type"));
        }
    }
    
    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!NestedModule.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'NestedModule' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<NestedModule> thisAdapter = gson.getDelegateAdapter(this, TypeToken.get(NestedModule.class));
            
            return (TypeAdapter<T>) new TypeAdapter<NestedModule>() {
                @Override
                public void write(JsonWriter out, NestedModule value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }
                
                @Override
                public NestedModule read(JsonReader in) throws IOException {
                    JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                    validateJsonObject(jsonObj);
                    return thisAdapter.fromJsonTree(jsonObj);
                }
                
            }.nullSafe();
        }
    }
    
    /**
     * Create an instance of NestedModule given an JSON string
     *
     * @param jsonString JSON string
     *
     * @return An instance of NestedModule
     *
     * @throws IOException if the JSON string is invalid with respect to NestedModule
     */
    public static NestedModule fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, NestedModule.class);
    }
    
    /**
     * Convert an instance of NestedModule to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

