/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.codemakers.netbox.client.JSON;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.jackson.nullable.JsonNullable;

import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.*;
import java.util.Map.Entry;

/**
 * Platform
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-29T15:14:28.278845400+02:00[Europe/Berlin]")
public class Platform {
    public static final String SERIALIZED_NAME_ID = "id";
    @SerializedName(SERIALIZED_NAME_ID)
    private Integer id;
    
    public static final String SERIALIZED_NAME_URL = "url";
    @SerializedName(SERIALIZED_NAME_URL)
    private URI url;
    
    public static final String SERIALIZED_NAME_DISPLAY = "display";
    @SerializedName(SERIALIZED_NAME_DISPLAY)
    private String display;
    
    public static final String SERIALIZED_NAME_NAME = "name";
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    
    public static final String SERIALIZED_NAME_SLUG = "slug";
    @SerializedName(SERIALIZED_NAME_SLUG)
    private String slug;
    
    public static final String SERIALIZED_NAME_MANUFACTURER = "manufacturer";
    @SerializedName(SERIALIZED_NAME_MANUFACTURER)
    private NestedManufacturer manufacturer;
    
    public static final String SERIALIZED_NAME_NAPALM_DRIVER = "napalm_driver";
    @SerializedName(SERIALIZED_NAME_NAPALM_DRIVER)
    private String napalmDriver;
    
    public static final String SERIALIZED_NAME_NAPALM_ARGS = "napalm_args";
    @SerializedName(SERIALIZED_NAME_NAPALM_ARGS)
    private String napalmArgs;
    
    public static final String SERIALIZED_NAME_DESCRIPTION = "description";
    @SerializedName(SERIALIZED_NAME_DESCRIPTION)
    private String description;
    
    public static final String SERIALIZED_NAME_TAGS = "tags";
    @SerializedName(SERIALIZED_NAME_TAGS)
    private List<NestedTag> tags = null;
    
    public static final String SERIALIZED_NAME_CUSTOM_FIELDS = "custom_fields";
    @SerializedName(SERIALIZED_NAME_CUSTOM_FIELDS)
    private Object customFields;
    
    public static final String SERIALIZED_NAME_CREATED = "created";
    @SerializedName(SERIALIZED_NAME_CREATED)
    private OffsetDateTime created;
    
    public static final String SERIALIZED_NAME_LAST_UPDATED = "last_updated";
    @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
    private OffsetDateTime lastUpdated;
    
    public static final String SERIALIZED_NAME_DEVICE_COUNT = "device_count";
    @SerializedName(SERIALIZED_NAME_DEVICE_COUNT)
    private Integer deviceCount;
    
    public static final String SERIALIZED_NAME_VIRTUALMACHINE_COUNT = "virtualmachine_count";
    @SerializedName(SERIALIZED_NAME_VIRTUALMACHINE_COUNT)
    private Integer virtualmachineCount;
    
    public Platform() {
    }
    
    
    public Platform(Integer id, URI url, String display, OffsetDateTime created, OffsetDateTime lastUpdated, Integer deviceCount, Integer virtualmachineCount) {
        this();
        this.id = id;
        this.url = url;
        this.display = display;
        this.created = created;
        this.lastUpdated = lastUpdated;
        this.deviceCount = deviceCount;
        this.virtualmachineCount = virtualmachineCount;
    }
    
    /**
     * Get id
     *
     * @return id
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Integer getId() {
        return id;
    }
    
    
    /**
     * Get url
     *
     * @return url
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public URI getUrl() {
        return url;
    }
    
    
    /**
     * Get display
     *
     * @return display
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public String getDisplay() {
        return display;
    }
    
    
    public Platform name(String name) {
        
        this.name = name;
        return this;
    }
    
    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    
    public String getName() {
        return name;
    }
    
    
    public void setName(String name) {
        this.name = name;
    }
    
    
    public Platform slug(String slug) {
        
        this.slug = slug;
        return this;
    }
    
    /**
     * Get slug
     *
     * @return slug
     **/
    @javax.annotation.Nonnull
    @ApiModelProperty(required = true, value = "")
    
    public String getSlug() {
        return slug;
    }
    
    
    public void setSlug(String slug) {
        this.slug = slug;
    }
    
    
    public Platform manufacturer(NestedManufacturer manufacturer) {
        
        this.manufacturer = manufacturer;
        return this;
    }
    
    /**
     * Get manufacturer
     *
     * @return manufacturer
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public NestedManufacturer getManufacturer() {
        return manufacturer;
    }
    
    
    public void setManufacturer(NestedManufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }
    
    
    public Platform napalmDriver(String napalmDriver) {
        
        this.napalmDriver = napalmDriver;
        return this;
    }
    
    /**
     * The name of the NAPALM driver to use when interacting with devices
     *
     * @return napalmDriver
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "The name of the NAPALM driver to use when interacting with devices")
    
    public String getNapalmDriver() {
        return napalmDriver;
    }
    
    
    public void setNapalmDriver(String napalmDriver) {
        this.napalmDriver = napalmDriver;
    }
    
    
    public Platform napalmArgs(String napalmArgs) {
        
        this.napalmArgs = napalmArgs;
        return this;
    }
    
    /**
     * Additional arguments to pass when initiating the NAPALM driver (JSON format)
     *
     * @return napalmArgs
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Additional arguments to pass when initiating the NAPALM driver (JSON format)")
    
    public String getNapalmArgs() {
        return napalmArgs;
    }
    
    
    public void setNapalmArgs(String napalmArgs) {
        this.napalmArgs = napalmArgs;
    }
    
    
    public Platform description(String description) {
        
        this.description = description;
        return this;
    }
    
    /**
     * Get description
     *
     * @return description
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public String getDescription() {
        return description;
    }
    
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    
    public Platform tags(List<NestedTag> tags) {
        
        this.tags = tags;
        return this;
    }
    
    public Platform addTagsItem(NestedTag tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }
    
    /**
     * Get tags
     *
     * @return tags
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public List<NestedTag> getTags() {
        return tags;
    }
    
    
    public void setTags(List<NestedTag> tags) {
        this.tags = tags;
    }
    
    
    public Platform customFields(Object customFields) {
        
        this.customFields = customFields;
        return this;
    }
    
    /**
     * Get customFields
     *
     * @return customFields
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Object getCustomFields() {
        return customFields;
    }
    
    
    public void setCustomFields(Object customFields) {
        this.customFields = customFields;
    }
    
    
    /**
     * Get created
     *
     * @return created
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public OffsetDateTime getCreated() {
        return created;
    }
    
    
    /**
     * Get lastUpdated
     *
     * @return lastUpdated
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public OffsetDateTime getLastUpdated() {
        return lastUpdated;
    }
    
    
    /**
     * Get deviceCount
     *
     * @return deviceCount
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Integer getDeviceCount() {
        return deviceCount;
    }
    
    
    /**
     * Get virtualmachineCount
     *
     * @return virtualmachineCount
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")
    
    public Integer getVirtualmachineCount() {
        return virtualmachineCount;
    }
    
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Platform platform = (Platform) o;
        return Objects.equals(this.id, platform.id) && Objects.equals(this.url, platform.url) && Objects.equals(this.display, platform.display) && Objects.equals(this.name, platform.name) && Objects.equals(this.slug, platform.slug) && Objects.equals(this.manufacturer, platform.manufacturer) && Objects.equals(this.napalmDriver, platform.napalmDriver) && Objects.equals(this.napalmArgs, platform.napalmArgs) && Objects.equals(this.description, platform.description) && Objects.equals(this.tags, platform.tags) && Objects.equals(this.customFields, platform.customFields) && Objects.equals(this.created, platform.created) && Objects.equals(this.lastUpdated, platform.lastUpdated) && Objects.equals(this.deviceCount, platform.deviceCount) && Objects.equals(this.virtualmachineCount, platform.virtualmachineCount);
    }
    
    private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
        return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(id, url, display, name, slug, manufacturer, napalmDriver, napalmArgs, description, tags, customFields, created, lastUpdated, deviceCount, virtualmachineCount);
    }
    
    private static <T> int hashCodeNullable(JsonNullable<T> a) {
        if (a == null) {
            return 1;
        }
        return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Platform {\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    display: ").append(toIndentedString(display)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
        sb.append("    manufacturer: ").append(toIndentedString(manufacturer)).append("\n");
        sb.append("    napalmDriver: ").append(toIndentedString(napalmDriver)).append("\n");
        sb.append("    napalmArgs: ").append(toIndentedString(napalmArgs)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
        sb.append("    created: ").append(toIndentedString(created)).append("\n");
        sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
        sb.append("    deviceCount: ").append(toIndentedString(deviceCount)).append("\n");
        sb.append("    virtualmachineCount: ").append(toIndentedString(virtualmachineCount)).append("\n");
        sb.append("}");
        return sb.toString();
    }
    
    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
    
    
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;
    
    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("id");
        openapiFields.add("url");
        openapiFields.add("display");
        openapiFields.add("name");
        openapiFields.add("slug");
        openapiFields.add("manufacturer");
        openapiFields.add("napalm_driver");
        openapiFields.add("napalm_args");
        openapiFields.add("description");
        openapiFields.add("tags");
        openapiFields.add("custom_fields");
        openapiFields.add("created");
        openapiFields.add("last_updated");
        openapiFields.add("device_count");
        openapiFields.add("virtualmachine_count");
        
        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
        openapiRequiredFields.add("name");
        openapiRequiredFields.add("slug");
    }
    
    /**
     * Validates the JSON Object and throws an exception if issues found
     *
     * @param jsonObj JSON Object
     *
     * @throws IOException if the JSON Object is invalid with respect to Platform
     */
    public static void validateJsonObject(JsonObject jsonObj) throws IOException {
        if (jsonObj == null) {
            if (Platform.openapiRequiredFields.isEmpty()) {
                return;
            } else { // has required fields
                throw new IllegalArgumentException(String.format("The required field(s) %s in Platform is not found in the empty JSON string", Platform.openapiRequiredFields.toString()));
            }
        }
        
        Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
        // check to see if the JSON string contains additional fields
        for (Entry<String, JsonElement> entry : entries) {
            if (!Platform.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Platform` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
            }
        }
        
        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : Platform.openapiRequiredFields) {
            if (jsonObj.get(requiredField) == null) {
                throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
            }
        }
        if (jsonObj.get("url") != null && !jsonObj.get("url").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url")
                    .toString()));
        }
        if (jsonObj.get("display") != null && !jsonObj.get("display").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `display` to be a primitive type in the JSON string but got `%s`", jsonObj.get("display")
                    .toString()));
        }
        if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name")
                    .toString()));
        }
        if (jsonObj.get("slug") != null && !jsonObj.get("slug").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slug")
                    .toString()));
        }
        // validate the optional field `manufacturer`
        if (jsonObj.getAsJsonObject("manufacturer") != null) {
            NestedManufacturer.validateJsonObject(jsonObj.getAsJsonObject("manufacturer"));
        }
        if (jsonObj.get("napalm_driver") != null && !jsonObj.get("napalm_driver").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `napalm_driver` to be a primitive type in the JSON string but got `%s`", jsonObj.get("napalm_driver")
                    .toString()));
        }
        if (jsonObj.get("napalm_args") != null && !jsonObj.get("napalm_args").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `napalm_args` to be a primitive type in the JSON string but got `%s`", jsonObj.get("napalm_args")
                    .toString()));
        }
        if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description")
                    .toString()));
        }
        JsonArray jsonArraytags = jsonObj.getAsJsonArray("tags");
        if (jsonArraytags != null) {
            // ensure the json data is an array
            if (!jsonObj.get("tags").isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags")
                        .toString()));
            }
            
            // validate the optional field `tags` (array)
            for (int i = 0; i < jsonArraytags.size(); i++) {
                NestedTag.validateJsonObject(jsonArraytags.get(i).getAsJsonObject());
            }
            ;
        }
    }
    
    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!Platform.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'Platform' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Platform> thisAdapter = gson.getDelegateAdapter(this, TypeToken.get(Platform.class));
            
            return (TypeAdapter<T>) new TypeAdapter<Platform>() {
                @Override
                public void write(JsonWriter out, Platform value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }
                
                @Override
                public Platform read(JsonReader in) throws IOException {
                    JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
                    validateJsonObject(jsonObj);
                    return thisAdapter.fromJsonTree(jsonObj);
                }
                
            }.nullSafe();
        }
    }
    
    /**
     * Create an instance of Platform given an JSON string
     *
     * @param jsonString JSON string
     *
     * @return An instance of Platform
     *
     * @throws IOException if the JSON string is invalid with respect to Platform
     */
    public static Platform fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, Platform.class);
    }
    
    /**
     * Convert an instance of Platform to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

