/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.codemakers.netbox.client.model.NestedTag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * WritableIPRange
 */
@JsonPropertyOrder({
  WritableIPRange.JSON_PROPERTY_ID,
  WritableIPRange.JSON_PROPERTY_URL,
  WritableIPRange.JSON_PROPERTY_DISPLAY,
  WritableIPRange.JSON_PROPERTY_FAMILY,
  WritableIPRange.JSON_PROPERTY_START_ADDRESS,
  WritableIPRange.JSON_PROPERTY_END_ADDRESS,
  WritableIPRange.JSON_PROPERTY_SIZE,
  WritableIPRange.JSON_PROPERTY_VRF,
  WritableIPRange.JSON_PROPERTY_TENANT,
  WritableIPRange.JSON_PROPERTY_STATUS,
  WritableIPRange.JSON_PROPERTY_ROLE,
  WritableIPRange.JSON_PROPERTY_DESCRIPTION,
  WritableIPRange.JSON_PROPERTY_TAGS,
  WritableIPRange.JSON_PROPERTY_CUSTOM_FIELDS,
  WritableIPRange.JSON_PROPERTY_CREATED,
  WritableIPRange.JSON_PROPERTY_LAST_UPDATED,
  WritableIPRange.JSON_PROPERTY_CHILDREN
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-31T15:10:46.540964900+02:00[Europe/Berlin]")
public class WritableIPRange {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_URL = "url";
  private URI url;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  private String display;

  public static final String JSON_PROPERTY_FAMILY = "family";
  private String family;

  public static final String JSON_PROPERTY_START_ADDRESS = "start_address";
  private String startAddress;

  public static final String JSON_PROPERTY_END_ADDRESS = "end_address";
  private String endAddress;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Integer size;

  public static final String JSON_PROPERTY_VRF = "vrf";
  private JsonNullable<Integer> vrf = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TENANT = "tenant";
  private JsonNullable<Integer> tenant = JsonNullable.<Integer>undefined();

  /**
   * Operational status of this range
   */
  public enum StatusEnum {
    ACTIVE("active"),
    
    RESERVED("reserved"),
    
    DEPRECATED("deprecated"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_ROLE = "role";
  private JsonNullable<Integer> role = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<NestedTag> tags = null;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  private Object customFields;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  private Integer children;

  public WritableIPRange() { 
  }

  @JsonCreator
  public WritableIPRange(
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_URL) URI url, 
    @JsonProperty(JSON_PROPERTY_DISPLAY) String display, 
    @JsonProperty(JSON_PROPERTY_FAMILY) String family, 
    @JsonProperty(JSON_PROPERTY_SIZE) Integer size, 
    @JsonProperty(JSON_PROPERTY_CREATED) OffsetDateTime created, 
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED) OffsetDateTime lastUpdated, 
    @JsonProperty(JSON_PROPERTY_CHILDREN) Integer children
  ) {
  this();
    this.id = id;
    this.url = url;
    this.display = display;
    this.family = family;
    this.size = size;
    this.created = created;
    this.lastUpdated = lastUpdated;
    this.children = children;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }




   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUrl() {
    return url;
  }




   /**
   * Get display
   * @return display
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplay() {
    return display;
  }




   /**
   * Get family
   * @return family
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FAMILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFamily() {
    return family;
  }




  public WritableIPRange startAddress(String startAddress) {
    this.startAddress = startAddress;
    return this;
  }

   /**
   * IPv4 or IPv6 address (with mask)
   * @return startAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "IPv4 or IPv6 address (with mask)")
  @JsonProperty(JSON_PROPERTY_START_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartAddress() {
    return startAddress;
  }


  @JsonProperty(JSON_PROPERTY_START_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartAddress(String startAddress) {
    this.startAddress = startAddress;
  }


  public WritableIPRange endAddress(String endAddress) {
    this.endAddress = endAddress;
    return this;
  }

   /**
   * IPv4 or IPv6 address (with mask)
   * @return endAddress
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "IPv4 or IPv6 address (with mask)")
  @JsonProperty(JSON_PROPERTY_END_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEndAddress() {
    return endAddress;
  }


  @JsonProperty(JSON_PROPERTY_END_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEndAddress(String endAddress) {
    this.endAddress = endAddress;
  }


   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSize() {
    return size;
  }




  public WritableIPRange vrf(Integer vrf) {
    this.vrf = JsonNullable.<Integer>of(vrf);
    return this;
  }

   /**
   * Get vrf
   * @return vrf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getVrf() {
        return vrf.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VRF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getVrf_JsonNullable() {
    return vrf;
  }
  
  @JsonProperty(JSON_PROPERTY_VRF)
  public void setVrf_JsonNullable(JsonNullable<Integer> vrf) {
    this.vrf = vrf;
  }

  public void setVrf(Integer vrf) {
    this.vrf = JsonNullable.<Integer>of(vrf);
  }


  public WritableIPRange tenant(Integer tenant) {
    this.tenant = JsonNullable.<Integer>of(tenant);
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getTenant() {
        return tenant.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TENANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTenant_JsonNullable() {
    return tenant;
  }
  
  @JsonProperty(JSON_PROPERTY_TENANT)
  public void setTenant_JsonNullable(JsonNullable<Integer> tenant) {
    this.tenant = tenant;
  }

  public void setTenant(Integer tenant) {
    this.tenant = JsonNullable.<Integer>of(tenant);
  }


  public WritableIPRange status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Operational status of this range
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Operational status of this range")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public WritableIPRange role(Integer role) {
    this.role = JsonNullable.<Integer>of(role);
    return this;
  }

   /**
   * The primary function of this range
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The primary function of this range")
  @JsonIgnore

  public Integer getRole() {
        return role.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getRole_JsonNullable() {
    return role;
  }
  
  @JsonProperty(JSON_PROPERTY_ROLE)
  public void setRole_JsonNullable(JsonNullable<Integer> role) {
    this.role = role;
  }

  public void setRole(Integer role) {
    this.role = JsonNullable.<Integer>of(role);
  }


  public WritableIPRange description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public WritableIPRange tags(List<NestedTag> tags) {
    this.tags = tags;
    return this;
  }

  public WritableIPRange addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<NestedTag> tags) {
    this.tags = tags;
  }


  public WritableIPRange customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }




   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }




   /**
   * Get children
   * @return children
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChildren() {
    return children;
  }




  /**
   * Return true if this WritableIPRange object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritableIPRange writableIPRange = (WritableIPRange) o;
    return Objects.equals(this.id, writableIPRange.id) &&
        Objects.equals(this.url, writableIPRange.url) &&
        Objects.equals(this.display, writableIPRange.display) &&
        Objects.equals(this.family, writableIPRange.family) &&
        Objects.equals(this.startAddress, writableIPRange.startAddress) &&
        Objects.equals(this.endAddress, writableIPRange.endAddress) &&
        Objects.equals(this.size, writableIPRange.size) &&
        equalsNullable(this.vrf, writableIPRange.vrf) &&
        equalsNullable(this.tenant, writableIPRange.tenant) &&
        Objects.equals(this.status, writableIPRange.status) &&
        equalsNullable(this.role, writableIPRange.role) &&
        Objects.equals(this.description, writableIPRange.description) &&
        Objects.equals(this.tags, writableIPRange.tags) &&
        Objects.equals(this.customFields, writableIPRange.customFields) &&
        Objects.equals(this.created, writableIPRange.created) &&
        Objects.equals(this.lastUpdated, writableIPRange.lastUpdated) &&
        Objects.equals(this.children, writableIPRange.children);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, display, family, startAddress, endAddress, size, hashCodeNullable(vrf), hashCodeNullable(tenant), status, hashCodeNullable(role), description, tags, customFields, created, lastUpdated, children);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritableIPRange {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    startAddress: ").append(toIndentedString(startAddress)).append("\n");
    sb.append("    endAddress: ").append(toIndentedString(endAddress)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

