/*
 * NetBox API
 * API to access NetBox
 *
 * The version of the OpenAPI document: 3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.codemakers.netbox.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.codemakers.netbox.client.model.NestedTag;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * WritablePrefix
 */
@JsonPropertyOrder({
  WritablePrefix.JSON_PROPERTY_ID,
  WritablePrefix.JSON_PROPERTY_URL,
  WritablePrefix.JSON_PROPERTY_DISPLAY,
  WritablePrefix.JSON_PROPERTY_FAMILY,
  WritablePrefix.JSON_PROPERTY_PREFIX,
  WritablePrefix.JSON_PROPERTY_SITE,
  WritablePrefix.JSON_PROPERTY_VRF,
  WritablePrefix.JSON_PROPERTY_TENANT,
  WritablePrefix.JSON_PROPERTY_VLAN,
  WritablePrefix.JSON_PROPERTY_STATUS,
  WritablePrefix.JSON_PROPERTY_ROLE,
  WritablePrefix.JSON_PROPERTY_IS_POOL,
  WritablePrefix.JSON_PROPERTY_MARK_UTILIZED,
  WritablePrefix.JSON_PROPERTY_DESCRIPTION,
  WritablePrefix.JSON_PROPERTY_TAGS,
  WritablePrefix.JSON_PROPERTY_CUSTOM_FIELDS,
  WritablePrefix.JSON_PROPERTY_CREATED,
  WritablePrefix.JSON_PROPERTY_LAST_UPDATED,
  WritablePrefix.JSON_PROPERTY_CHILDREN,
  WritablePrefix.JSON_PROPERTY_DEPTH
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-31T15:10:46.540964900+02:00[Europe/Berlin]")
public class WritablePrefix {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_URL = "url";
  private URI url;

  public static final String JSON_PROPERTY_DISPLAY = "display";
  private String display;

  public static final String JSON_PROPERTY_FAMILY = "family";
  private String family;

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  private String prefix;

  public static final String JSON_PROPERTY_SITE = "site";
  private JsonNullable<Integer> site = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_VRF = "vrf";
  private JsonNullable<Integer> vrf = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TENANT = "tenant";
  private JsonNullable<Integer> tenant = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_VLAN = "vlan";
  private JsonNullable<Integer> vlan = JsonNullable.<Integer>undefined();

  /**
   * Operational status of this prefix
   */
  public enum StatusEnum {
    CONTAINER("container"),
    
    ACTIVE("active"),
    
    RESERVED("reserved"),
    
    DEPRECATED("deprecated"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_ROLE = "role";
  private JsonNullable<Integer> role = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_IS_POOL = "is_pool";
  private Boolean isPool;

  public static final String JSON_PROPERTY_MARK_UTILIZED = "mark_utilized";
  private Boolean markUtilized;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<NestedTag> tags = null;

  public static final String JSON_PROPERTY_CUSTOM_FIELDS = "custom_fields";
  private Object customFields;

  public static final String JSON_PROPERTY_CREATED = "created";
  private OffsetDateTime created;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  private OffsetDateTime lastUpdated;

  public static final String JSON_PROPERTY_CHILDREN = "children";
  private Integer children;

  public static final String JSON_PROPERTY_DEPTH = "_depth";
  private Integer depth;

  public WritablePrefix() { 
  }

  @JsonCreator
  public WritablePrefix(
    @JsonProperty(JSON_PROPERTY_ID) Integer id, 
    @JsonProperty(JSON_PROPERTY_URL) URI url, 
    @JsonProperty(JSON_PROPERTY_DISPLAY) String display, 
    @JsonProperty(JSON_PROPERTY_FAMILY) String family, 
    @JsonProperty(JSON_PROPERTY_CREATED) OffsetDateTime created, 
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED) OffsetDateTime lastUpdated, 
    @JsonProperty(JSON_PROPERTY_CHILDREN) Integer children, 
    @JsonProperty(JSON_PROPERTY_DEPTH) Integer depth
  ) {
  this();
    this.id = id;
    this.url = url;
    this.display = display;
    this.family = family;
    this.created = created;
    this.lastUpdated = lastUpdated;
    this.children = children;
    this.depth = depth;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }




   /**
   * Get url
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URI getUrl() {
    return url;
  }




   /**
   * Get display
   * @return display
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplay() {
    return display;
  }




   /**
   * Get family
   * @return family
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FAMILY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFamily() {
    return family;
  }




  public WritablePrefix prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * IPv4 or IPv6 network with mask
   * @return prefix
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "IPv4 or IPv6 network with mask")
  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPrefix() {
    return prefix;
  }


  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  public WritablePrefix site(Integer site) {
    this.site = JsonNullable.<Integer>of(site);
    return this;
  }

   /**
   * Get site
   * @return site
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getSite() {
        return site.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getSite_JsonNullable() {
    return site;
  }
  
  @JsonProperty(JSON_PROPERTY_SITE)
  public void setSite_JsonNullable(JsonNullable<Integer> site) {
    this.site = site;
  }

  public void setSite(Integer site) {
    this.site = JsonNullable.<Integer>of(site);
  }


  public WritablePrefix vrf(Integer vrf) {
    this.vrf = JsonNullable.<Integer>of(vrf);
    return this;
  }

   /**
   * Get vrf
   * @return vrf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getVrf() {
        return vrf.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VRF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getVrf_JsonNullable() {
    return vrf;
  }
  
  @JsonProperty(JSON_PROPERTY_VRF)
  public void setVrf_JsonNullable(JsonNullable<Integer> vrf) {
    this.vrf = vrf;
  }

  public void setVrf(Integer vrf) {
    this.vrf = JsonNullable.<Integer>of(vrf);
  }


  public WritablePrefix tenant(Integer tenant) {
    this.tenant = JsonNullable.<Integer>of(tenant);
    return this;
  }

   /**
   * Get tenant
   * @return tenant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getTenant() {
        return tenant.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TENANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTenant_JsonNullable() {
    return tenant;
  }
  
  @JsonProperty(JSON_PROPERTY_TENANT)
  public void setTenant_JsonNullable(JsonNullable<Integer> tenant) {
    this.tenant = tenant;
  }

  public void setTenant(Integer tenant) {
    this.tenant = JsonNullable.<Integer>of(tenant);
  }


  public WritablePrefix vlan(Integer vlan) {
    this.vlan = JsonNullable.<Integer>of(vlan);
    return this;
  }

   /**
   * Get vlan
   * @return vlan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonIgnore

  public Integer getVlan() {
        return vlan.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VLAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getVlan_JsonNullable() {
    return vlan;
  }
  
  @JsonProperty(JSON_PROPERTY_VLAN)
  public void setVlan_JsonNullable(JsonNullable<Integer> vlan) {
    this.vlan = vlan;
  }

  public void setVlan(Integer vlan) {
    this.vlan = JsonNullable.<Integer>of(vlan);
  }


  public WritablePrefix status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Operational status of this prefix
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Operational status of this prefix")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public WritablePrefix role(Integer role) {
    this.role = JsonNullable.<Integer>of(role);
    return this;
  }

   /**
   * The primary function of this prefix
   * @return role
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The primary function of this prefix")
  @JsonIgnore

  public Integer getRole() {
        return role.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getRole_JsonNullable() {
    return role;
  }
  
  @JsonProperty(JSON_PROPERTY_ROLE)
  public void setRole_JsonNullable(JsonNullable<Integer> role) {
    this.role = role;
  }

  public void setRole(Integer role) {
    this.role = JsonNullable.<Integer>of(role);
  }


  public WritablePrefix isPool(Boolean isPool) {
    this.isPool = isPool;
    return this;
  }

   /**
   * All IP addresses within this prefix are considered usable
   * @return isPool
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "All IP addresses within this prefix are considered usable")
  @JsonProperty(JSON_PROPERTY_IS_POOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsPool() {
    return isPool;
  }


  @JsonProperty(JSON_PROPERTY_IS_POOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPool(Boolean isPool) {
    this.isPool = isPool;
  }


  public WritablePrefix markUtilized(Boolean markUtilized) {
    this.markUtilized = markUtilized;
    return this;
  }

   /**
   * Treat as 100% utilized
   * @return markUtilized
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Treat as 100% utilized")
  @JsonProperty(JSON_PROPERTY_MARK_UTILIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getMarkUtilized() {
    return markUtilized;
  }


  @JsonProperty(JSON_PROPERTY_MARK_UTILIZED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarkUtilized(Boolean markUtilized) {
    this.markUtilized = markUtilized;
  }


  public WritablePrefix description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public WritablePrefix tags(List<NestedTag> tags) {
    this.tags = tags;
    return this;
  }

  public WritablePrefix addTagsItem(NestedTag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<NestedTag> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<NestedTag> tags) {
    this.tags = tags;
  }


  public WritablePrefix customFields(Object customFields) {
    this.customFields = customFields;
    return this;
  }

   /**
   * Get customFields
   * @return customFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCustomFields() {
    return customFields;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomFields(Object customFields) {
    this.customFields = customFields;
  }


   /**
   * Get created
   * @return created
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }




   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }




   /**
   * Get children
   * @return children
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHILDREN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getChildren() {
    return children;
  }




   /**
   * Get depth
   * @return depth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEPTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDepth() {
    return depth;
  }




  /**
   * Return true if this WritablePrefix object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WritablePrefix writablePrefix = (WritablePrefix) o;
    return Objects.equals(this.id, writablePrefix.id) &&
        Objects.equals(this.url, writablePrefix.url) &&
        Objects.equals(this.display, writablePrefix.display) &&
        Objects.equals(this.family, writablePrefix.family) &&
        Objects.equals(this.prefix, writablePrefix.prefix) &&
        equalsNullable(this.site, writablePrefix.site) &&
        equalsNullable(this.vrf, writablePrefix.vrf) &&
        equalsNullable(this.tenant, writablePrefix.tenant) &&
        equalsNullable(this.vlan, writablePrefix.vlan) &&
        Objects.equals(this.status, writablePrefix.status) &&
        equalsNullable(this.role, writablePrefix.role) &&
        Objects.equals(this.isPool, writablePrefix.isPool) &&
        Objects.equals(this.markUtilized, writablePrefix.markUtilized) &&
        Objects.equals(this.description, writablePrefix.description) &&
        Objects.equals(this.tags, writablePrefix.tags) &&
        Objects.equals(this.customFields, writablePrefix.customFields) &&
        Objects.equals(this.created, writablePrefix.created) &&
        Objects.equals(this.lastUpdated, writablePrefix.lastUpdated) &&
        Objects.equals(this.children, writablePrefix.children) &&
        Objects.equals(this.depth, writablePrefix.depth);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, url, display, family, prefix, hashCodeNullable(site), hashCodeNullable(vrf), hashCodeNullable(tenant), hashCodeNullable(vlan), status, hashCodeNullable(role), isPool, markUtilized, description, tags, customFields, created, lastUpdated, children, depth);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WritablePrefix {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("    vrf: ").append(toIndentedString(vrf)).append("\n");
    sb.append("    tenant: ").append(toIndentedString(tenant)).append("\n");
    sb.append("    vlan: ").append(toIndentedString(vlan)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    isPool: ").append(toIndentedString(isPool)).append("\n");
    sb.append("    markUtilized: ").append(toIndentedString(markUtilized)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    customFields: ").append(toIndentedString(customFields)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    depth: ").append(toIndentedString(depth)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

