name: Publish snapshot packages to GitHub Packages and Sonatype OSSRH and create a GitHub release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish NetBox API
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle run publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          MAVEN_URL_RELEASES: ${{ secrets.MAVEN_URL_RELEASES }}
          MAVEN_URL_SNAPSHOTS: ${{ secrets.MAVEN_URL_SNAPSHOTS }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar,~/build/libs/*.jar"
          bodyFile: "CHANGELOG.md"
          artifactErrorsFailBuild: false
          prerelease: ${{ endsWith(github.ref_name, '-SNAPSHOT') }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete the oldest Pre-Releases from GitHub Packages, but keep at least 10 Versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: de.codemakers.netbox.netbox-java-client
          min-versions-to-keep: 10
          delete-only-pre-release-versions: true