name: Publish snapshot packages to GitHub Packages and Maven and create a GitHub release

on:
  push:
    tags:
      - 'v*.*.*-SNAPSHOT*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Gradle run build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Gradle run publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_URL_RELEASES: ${{ secrets.MAVEN_URL_RELEASES }}
          MAVEN_URL_SNAPSHOTS: ${{ secrets.MAVEN_URL_SNAPSHOTS }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Delete the oldest Packages on GitHub, but keep at least 5 Versions
        uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          keep: 5
          names: |
            de.codemakers.netbox

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar,dist/*.jar"
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}